config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("peter_lang.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("peter_lang.home.urls")),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    path(
        "artwork/",
        include("peter_lang.artworks.urls", namespace="artworks"),
    ),
    path(
        "articles/",
        include("peter_lang.articles.urls", namespace="articles"),
    ),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

peter_lang/articles/urls.py
from django.urls import path

from .views import (
        ArticleCreate,
        ArticleList,
        ArticleDetail,
        ArticleUpdate,
        ArticleDelete,
        ArticlePublicList,
)

app_name = 'articles'
urlpatterns = [
    path('', ArticlePublicList.as_view(), name='list'),
    path('create', ArticleCreate.as_view(), name='create'),
    path('manage', ArticleList.as_view(), name='manage'),
    path('<str:slug>/', ArticleDetail.as_view(), name='detail'),
    path('<str:slug>/update', ArticleUpdate.as_view(), name='update'),
    path('<str:slug>/delete', ArticleDelete.as_view(), name='delete'),
]

peter_lang/home/urls.py
from django.urls import path

from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

peter_lang/users/urls.py
from django.urls import path

from peter_lang.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

peter_lang/articles/models.py
from django.db import models

from peter_lang.artworks.models import Artwork


class Article(models.Model):
    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length=128, unique=True)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    preview_picture = models.ForeignKey(Artwork, on_delete=models.SET_NULL, null=True)
    preview_text = models.TextField()
    is_published = models.BooleanField(default=True)

    def __str__(self):
        return self.name

peter_lang/artworks/models.py
from django.db import models


class Artwork(models.Model):
    name = models.CharField(max_length=128, unique=True)
    image = models.ImageField()
    slug = models.SlugField(max_length=128, unique=True)

    def __str__(self):
        return self.name

peter_lang/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

peter_lang/articles/forms.py
from django.forms import ModelForm

from .models import Article


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = [
                'name',
                'slug',
                'text',
                'preview_picture',
                'preview_text',
                'is_published',
        ]

peter_lang/artworks/forms.py
from django.forms import ModelForm

from .models import Artwork


class ArtworkForm(ModelForm):
    class Meta:
        model = Artwork
        fields = [
                'name',
                'slug',
                'image',
        ]

peter_lang/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

peter_lang/articles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import (
        CreateView,
        DeleteView,
        UpdateView
)
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy

from .forms import ArticleForm
from .models import Article


class ArticleCreate(
        LoginRequiredMixin,
        CreateView
):
    model = Article
    form_class = ArticleForm
    login_url = '/accounts/login/'
    success_url = reverse_lazy('articles:manage')


class ArticleList(
        LoginRequiredMixin,
        ListView,
):
    model = Article
    template_name = 'articles/article_management_list.html'

    def get_queryset(self):
        return super().get_queryset().order_by('-created_at')


class ArticlePublicList(ListView):
    model = Article
    template_name = 'articles/article_list.html'

    def get_queryset(self):
        return super().get_queryset().filter(is_published=True).order_by('-created_at')


class ArticleDetail(DetailView):
    model = Article


class ArticleDelete(
        LoginRequiredMixin,
        DeleteView,
):
    model = Article
    success_url = reverse_lazy('articles:manage')


class ArticleUpdate(
        LoginRequiredMixin,
        UpdateView,
):
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy('articles:manage')

peter_lang/artworks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import (
        CreateView,
        DeleteView,
        UpdateView,
)
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy

from .forms import ArtworkForm
from .models import Artwork


class ArtworkCreate(
        LoginRequiredMixin,
        CreateView
):
    model = Artwork
    form_class = ArtworkForm
    login_url = '/accounts/login/'
    success_url = reverse_lazy('artworks:list')


class ArtworkList(
        LoginRequiredMixin,
        ListView,
):
    model = Artwork


class ArtworkDelete(
        LoginRequiredMixin,
        DeleteView,
):
    model = Artwork
    success_url = reverse_lazy('artworks:list')


class ArtworkUpdate(
        LoginRequiredMixin,
        UpdateView,
):
    model = Artwork
    form_class = ArtworkForm
    success_url = reverse_lazy('artworks:list')

peter_lang/home/views.py
from django.views.generic.list import ListView

from peter_lang.artworks.models import Artwork
from peter_lang.articles.models import Article


class HomeView(ListView):
    model = Artwork
    template_name = 'pages/home.html'

    def get_queryset(self):
        return super().get_queryset().order_by('?')[:10]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_article'] = Article.objects.filter(is_published=True).last()

        return context

peter_lang/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

peter_lang/templates/articles/article_confirm_delete.html
{% extends "base.html" %}

{% block title %}DELETE {{ object.name }}{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <form method="post">
	{% csrf_token %}
	{{ form }}
	<input type="submit" value="Confirm delete?" />
    </form>
</div>
{% endblock %}

peter_lang/templates/articles/article_detail.html
{% extends "base.html" %}

{% block title %}{{ object.name }}{% endblock %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-md-9 text-center">
	<h1>{{ object.name }}</h1>
	<h5>{{ object.created_at|date:"d F Y" }}</h5>
	<br>
    </div>
</div>
<div class="row justify-content-center">
    <div class="col-md-9 text-justify">
	<p>{{ object.text | safe | linebreaks }}</p>
    </div>
</div>
{% endblock %}

peter_lang/templates/articles/article_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}
{% if object %}
Update {{ object.name }}
{% else %}
Create new article
{% endif %}
{% endblock %}

{% block content %}
{% if object %}
<h1>Update {{ object.name }}</h1>
{% else %}
<h1>New article</h1>
{% endif %}
<p>{{ form.errors }}</p>
{% if object %}
<form class="form-horizontal" method="post" action="{% url 'articles:update' object.slug %}">
{% else %}
<form class="form-horizontal" method="post" action="{% url 'articles:create' %}">
{% endif %}
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
	<div class="controls">
	    {% if object %}
	    <button type="submit" class="btn">Update</button>
	    {% else %}
	    <button type="submit" class="btn">Create</button>
	    {% endif %}
	</div>
    </div>
</form>
{% endblock %}

peter_lang/templates/articles/article_list.html
{% extends "base.html" %}

{% block title %}All articles{% endblock %}

{% block content %}
{% for article in object_list %}
<div class="row justify-content-center">
    <div class="col-md-9 text-center mb-3">
	<h1><a href="{{ article.slug }}">{{ article.name }}</a><h1>
	<h5>{{ article.created_at|date:"d F Y" }}</h5>
    </div>
</div>

{% if article.preview_picture %}
<div class="row justify-content-center">
    <div class="col-md-6 text-justify mb-3">
	<p>{{ article.preview_text }}</p>
    </div>
    <div class="col-md-3 mb-3 text-center">
	<img class="w-100" src="{{ article.preview_picture.image.url }}" alt="{{ article.preview_picture.name }}">
    </div>
</div>
{% else %}
<div class="row justify-content-center">
    <div class="col-md-9 text-justify">
	<p>{{ latest_article.preview_text }}</p>
    </div>
</div>
{% endif %}
{% if not forloop.last %}
<hr/>
{% endif %}
{% endfor %}
{% endblock %}

peter_lang/templates/articles/article_management_list.html
{% extends "base.html" %}

{% block title %}All articles{% endblock %}

{% block content %}
<h1>All articles</h1>
<h3><a href="/articles/create">Create new</a></h3>
<table class="table">
    {% for article in object_list %}
    <tr>
	<td><a href="/articles/{{ article.slug }}">{{ article.name }}</a></td>
	<td>{% if article.is_published %}Public{% else %}Private{% endif %}</td>
	<td><a href="/articles/{{ article.slug }}/update">Update</a></td>
	<td><a href="/articles/{{ article.slug }}/delete">Delete</a></td>
    </tr>
    {% endfor %}
</table>
{% endblock %}