config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path(
        "users/",
        include("peter_lang.users.urls", namespace="users"),
    ),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("peter_lang.home.urls")),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    path(
        "artwork/",
        include("peter_lang.artworks.urls", namespace="artworks"),
    ),
    path(
        "articles/",
        include("peter_lang.articles.urls", namespace="articles"),
    ),
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

peter_lang/articles/urls.py
from django.urls import path

from .views import (
        ArticleCreate,
        ArticleList,
        ArticleDetail,
        ArticleUpdate,
        ArticleDelete,
        ArticlePublicList,
)

app_name = 'articles'
urlpatterns = [
    path('', ArticlePublicList.as_view(), name='list'),
    path('create', ArticleCreate.as_view(), name='create'),
    path('manage', ArticleList.as_view(), name='manage'),
    path('<str:slug>/', ArticleDetail.as_view(), name='detail'),
    path('<str:slug>/update', ArticleUpdate.as_view(), name='update'),
    path('<str:slug>/delete', ArticleDelete.as_view(), name='delete'),
]

peter_lang/home/urls.py
from django.urls import path

from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
]

peter_lang/users/urls.py
from django.urls import path

from peter_lang.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

peter_lang/articles/models.py
from django.db import models

from peter_lang.artworks.models import Artwork


class Article(models.Model):
    name = models.CharField(max_length=128, unique=True)
    slug = models.SlugField(max_length=128, unique=True)
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    preview_picture = models.ForeignKey(Artwork, on_delete=models.SET_NULL, null=True)
    preview_text = models.TextField()
    is_published = models.BooleanField(default=True)

    def __str__(self):
        return self.name

peter_lang/artworks/models.py
from django.db import models


class Artwork(models.Model):
    name = models.CharField(max_length=128, unique=True)
    image = models.ImageField()
    slug = models.SlugField(max_length=128, unique=True)

    def __str__(self):
        return self.name

peter_lang/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

peter_lang/articles/forms.py
from django.forms import ModelForm

from .models import Article


class ArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = [
                'name',
                'slug',
                'text',
                'preview_picture',
                'preview_text',
                'is_published',
        ]

peter_lang/artworks/forms.py
from django.forms import ModelForm

from .models import Artwork


class ArtworkForm(ModelForm):
    class Meta:
        model = Artwork
        fields = [
                'name',
                'slug',
                'image',
        ]

peter_lang/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):

    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

peter_lang/articles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import (
        CreateView,
        DeleteView,
        UpdateView
)
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy

from .forms import ArticleForm
from .models import Article


class ArticleCreate(
        LoginRequiredMixin,
        CreateView
):
    model = Article
    form_class = ArticleForm
    login_url = '/accounts/login/'
    success_url = reverse_lazy('articles:manage')


class ArticleList(
        LoginRequiredMixin,
        ListView,
):
    model = Article
    template_name = 'articles/article_management_list.html'

    def get_queryset(self):
        return super().get_queryset().order_by('-created_at')


class ArticlePublicList(ListView):
    model = Article
    template_name = 'articles/article_list.html'

    def get_queryset(self):
        return super().get_queryset().filter(is_published=True).order_by('-created_at')


class ArticleDetail(DetailView):
    model = Article


class ArticleDelete(
        LoginRequiredMixin,
        DeleteView,
):
    model = Article
    success_url = reverse_lazy('articles:manage')


class ArticleUpdate(
        LoginRequiredMixin,
        UpdateView,
):
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy('articles:manage')

peter_lang/artworks/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import (
        CreateView,
        DeleteView,
        UpdateView,
)
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.urls import reverse_lazy

from .forms import ArtworkForm
from .models import Artwork


class ArtworkCreate(
        LoginRequiredMixin,
        CreateView
):
    model = Artwork
    form_class = ArtworkForm
    login_url = '/accounts/login/'
    success_url = reverse_lazy('artworks:list')


class ArtworkList(
        LoginRequiredMixin,
        ListView,
):
    model = Artwork


class ArtworkDelete(
        LoginRequiredMixin,
        DeleteView,
):
    model = Artwork
    success_url = reverse_lazy('artworks:list')


class ArtworkUpdate(
        LoginRequiredMixin,
        UpdateView,
):
    model = Artwork
    form_class = ArtworkForm
    success_url = reverse_lazy('artworks:list')

peter_lang/home/views.py
from django.views.generic.list import ListView

from peter_lang.artworks.models import Artwork
from peter_lang.articles.models import Article


class HomeView(ListView):
    model = Artwork
    template_name = 'pages/home.html'

    def get_queryset(self):
        return super().get_queryset().order_by('?')[:10]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['latest_article'] = Article.objects.filter(is_published=True).last()

        return context

peter_lang/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

peter_lang/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

peter_lang/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% load cookielaw_tags %}

<html lang="en">
    <head>
	<meta charset="utf-8">
	<meta http-equiv="x-ua-compatible" content="ie=edge">
	<title>{% block title %}Peter Lang{% endblock title %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta name="description" content="">
	<meta name="author" content="">

	<!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	    <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
	<![endif]-->

	<link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

	{% block css %}

	<!-- Latest compiled and minified Bootstrap 4.1.1 CSS -->
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">


	<!-- Your stuff: Third-party CSS libraries go here -->
	<link href="https://stackpath.bootstrapcdn.com/bootswatch/4.3.1/cosmo/bootstrap.min.css" rel="stylesheet" integrity="sha384-uhut8PejFZO8994oEgm/ZfAv0mW1/b83nczZzSwElbeILxwkN491YQXsCFTE6+nx" crossorigin="anonymous">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">

	<!-- This file stores project-specific CSS -->

	<link href="{% static "cookielaw/css/cookielaw.css"%}" rel="stylesheet" />

	<link href="{% static 'css/project.css' %}" rel="stylesheet">
	<link href="{% static 'css/style.css' %}" rel="stylesheet">
	<link href="{% static 'css/extras.css' %}" rel="stylesheet">

	{% endblock %}

    </head>

    <body>

	{% cookielaw_banner %}

	<div class="mb-1 bg-light navbar">
	    <nav class="navbar-expand-md navbar-light container">
		<button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		    <span class="navbar-toggler-icon"></span>
		</button>
		<a class="navbar-brand" href="{% url 'home' %}">Peter Lang</a>

		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		    <ul class="navbar-nav mr-3 text-right">
			<li class="nav-item">
			    <a class="nav-link" href="{% url 'about' %}">About</a>
			</li>
			<li class="nav-item">
			    <a class="nav-link" href="{% url 'articles:list' %}">Articles</a>
			</li>
			{% if request.user.is_authenticated %}
			<li class="nav-item">
			    <a class="nav-link" href="{% url 'artworks:list' %}">{% trans "Manage Art" %}</a>
			</li>
			<li class="nav-item">
			    <a class="nav-link" href="{% url 'articles:manage' %}">{% trans "Manage Articles" %}</a>
			</li>
			<li class="nav-item">
			    {# URL provided by django-allauth/account/urls.py #}
			    <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
			</li>
			{% endif %}
		    </ul>
		</div>
	    </nav>
	</div>

	<div class="container wrap mt-5">

	    {% if messages %}
	    {% for message in messages %}
	    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
	    {% endfor %}
	    {% endif %}

	    {% block content %}
	    <p>Use this document as a way to quick start any new project.</p>
	    {% endblock content %}

	</div> <!-- /container -->
	<div class="bg-light">
	    <section class="footer container">
		<div class="row justify-content-center">
		    <div class="col-md-9" style="margin:2%;text-align:right">
			<h5>All text and images &copy; Peter Lang 2019</h5>
		    </div>
		</div>
	    </section>
	</div>
	{% block modal %}{% endblock modal %}


	<!-- Le javascript
     ================================================== -->
     <!-- Placed at the end of the document so the pages load faster -->
     {% block javascript %}

     <!-- Required by Bootstrap v4.1.1 -->
     <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
     <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

     <!-- Your stuff: Third-party javascript libraries go here -->

     <script src="{% static "cookielaw/js/cookielaw.js"%}" type="text/javascript"></script>

     <!-- place project specific Javascript in this file -->

     <script src="{% static 'js/project.js' %}"></script>

     {% endblock javascript %}

    </body>
</html>